export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

export const FETCH_PHOTOS = "FETCH_PHOTOS";
export const FETCH_PHOTOS_SUCCESS = "FETCH_PHOTOS_SUCCESS";
export const FETCH_PHOTOS_WITH_REFRESHING = "FETCH_PHOTOS_WITH_REFRESHING";


